jdk: oraclejdk8
language: scala
scala:
  - 2.11.8
  - 2.12.1
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"
  - "$HOME/.m2"
notifications:
  slack:
    secure: S6pcmclrj9vaqHOFMrjgYkF6wXrYF6nB5joYY0rqAwsmTLf7crXRVKZ8txlatpxMHc20Rbw8RQDM6tTka9wwBkHZZfErrcPsS84d5MU9siEkIY42/bAQwuYhxkcgilttgFmSwzLodE72giC/VMhIYCSOyOXIxuR0VtBiPD9Inm9QZ35dZDx3P3nbnaOC4fk+BjdbrX1LB8YL9z5Gy/9TqI90w0FV85XMef75EnSgpqeMD/GMB5hIg+arWVnC2S6hZ91PPCcxCTKBYDjwqUac8mFW/sMFT/yrb2c0NE6ZQqa3dlx/XFyC1X6+7DjJli2Y8OU+FPjY1tQC8JxgVFTbddIgCdUM/5be4uHN/KNs/yF7w1g06ZXK4jhJxxpL4zWINlqDrDmLaqhAtPQkc2CqL3g8MCwYxBbxZY4aFyPfZD7YLdQXDzJZNcfXn9RQQh5y+/zexbGc1zZ/XUo5bK3VbElSs+o2ErI+Sze0FaiK8fW+QeitBdGvjMY7YVKi0Zzf5Dxx1wwxiHR1PQ1r0hA8YZQxwwdpa5lWLFlSVu2w+upPtXqfINMeFktQPbOs1JWIvUvLV0A38dS6R/DsM/W1a3OEVbHQ0Z6OV1nffDnGYPLUl5kRDPFuYYugmCpQHW73lqJdiM0O+Ote4eOQniL1rcajtt+V5cn1/JRWzdJ4PH0=
    secure: j3MjMQbj0k+k6+b5v/fcqy4HYJqAlIi41VoNPI1mtaiPOccvkDUWh/2APzFujTPOXb4j6ujN/ogTBXnbY3cemYTfK8qdt2o6v0U7FbxVdjOgUKzDrsfMoKaDFAIIcJ+viXodJ44qKHRtURhIdNR+3gztasRpfeFUtRbZz0jC71VwrxS/kPN7f3EzeHZLEmOQDWcBq1uL9gkRfQWy9ay6REJv0Te+S+QhcV+5c1xku321Z8pxNp+A7waT+nnnCVWCsB/tve0NASDRR51JJGfJDh3SxgFDikP4IG5fdNnrd6kcjjyeLBJtvZ8uiN9u5KrXX1SeIOx9UcNmZs6jhSCgVRlCbz5aKT1Sx8XloxvBQC4U3Q3NQbgW5b4RM/kGE4xcr4Sg8FEGEu8XqzpGhhWRhgGpGneKCL73Y1LTPTSXm+gTmHoMYR4eeprlsDbQrSeNQAtO1zWRk7a9sR3RoJXzD4WO50vzHDajK6nc19xt8DchwUiPzzV9DB2bW8uOyiYtf7WgdX70Q57WntqJ7r4sk0pWC5B4krbO95YhyWxakCst9fWhXn1DmtwJ2tNnW7Oitlo3Gvny9Wmn+7f0gLJMlU1+JCtap3atWcR0VV7em53ycWMEPONr1SzmNks7t1xn3Qhe1mjldteBk+7WZeg72HUY8PSmz1X8NVur7hJT9PM=
before_install:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_cbef0ff679f7_key -iv $encrypted_cbef0ff679f7_iv -in devices.json.enc -out src/test/resources/devices.json -d ; fi
